Updates

diff --git a/machine/registry/01_daemon.yaml b/machine/registry/01_daemon.yaml
--- a/machine/registry/01_daemon.yaml
+++ b/machine/registry/01_daemon.yaml
@@ -4,8 +4,22 @@ metadata:
   name: setup-script
 data:
   setup.sh: |
-    sudo sed -i 's/127.0.0.1 localhost/127.0.0.1 registry localhost/g' /etc/hosts
-    echo "$TRUSTED_CERT" > /usr/local/share/ca-certificates/ca.crt && update-ca-certificates && systemctl restart k3s.service
+    #!/bin/bash
+
+    set -eu
+
+    sed -i 's/127.0.0.1[[:blank:]]*localhost/127.0.0.1 registry localhost/g' /etc/hosts
+    if [ -d "/usr/local/share/ca-certificates/" ]; then
+      echo "$TRUSTED_CERT" > /usr/local/share/ca-certificates/ca.crt
+      update-ca-certificates
+      systemctl restart k3s.service
+    elif [ -d "/etc/pki/ca-trust/source/anchors/" ]; then
+      echo "$TRUSTED_CERT" > /etc/pki/ca-trust/source/anchors/ca.crt
+      update-ca-trust
+    else
+      echo "Cannot install certificate"
+      exit 1
+    fi
 ---
 apiVersion: apps/v1
 kind: DaemonSet
